// Custom minimal MapLibre style with hillshade and white streets (no casing).
// Based on Protomaps grayscale theme + AWS Open Terrain hillshade.

const SOURCE = "protomaps";
const PROTOMAPS_KEY = "e719bed843250125";

export const style = {
  version: 8,
  name: "Minimal Hillshade",
  glyphs:
    "https://protomaps.github.io/basemaps-assets/fonts/{fontstack}/{range}.pbf",
  sprite:
    "https://protomaps.github.io/basemaps-assets/sprites/v4/grayscale",
  sources: {
    [SOURCE]: {
      type: "vector",
      url: `https://api.protomaps.com/tiles/v4.json?key=${PROTOMAPS_KEY}`,
      attribution:
        '<a href="https://protomaps.com">Protomaps</a> | <a href="https://openstreetmap.org">OSM</a>',
    },
    terrain: {
      type: "raster-dem",
      tiles: [
        "https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png",
      ],
      tileSize: 256,
      maxzoom: 15,
      encoding: "terrarium",
    },
  },
  layers: [
    // ── Background & earth ──────────────────────────────────────────
    {
      id: "background",
      type: "background",
      paint: { "background-color": "#e8e4e0" },
    },
    {
      id: "earth",
      type: "fill",
      source: SOURCE,
      "source-layer": "earth",
      paint: { "fill-color": "#ddd8d3" },
    },

    // ── Landcover (low zoom) ────────────────────────────────────────
    {
      id: "landcover",
      type: "fill",
      source: SOURCE,
      "source-layer": "landcover",
      paint: {
        "fill-color": "#d5d0cb",
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 5, 0.6, 7, 0],
      },
    },

    // ── Landuse ─────────────────────────────────────────────────────
    {
      id: "landuse_park",
      type: "fill",
      source: SOURCE,
      "source-layer": "landuse",
      filter: [
        "in",
        "kind",
        "national_park",
        "park",
        "cemetery",
        "nature_reserve",
        "forest",
        "grassland",
      ],
      paint: {
        "fill-color": "#d4ddd0",
        "fill-opacity": 0.5,
      },
    },
    {
      id: "landuse_urban_green",
      type: "fill",
      source: SOURCE,
      "source-layer": "landuse",
      filter: [
        "in",
        "kind",
        "garden",
        "golf_course",
        "playground",
        "recreation_ground",
        "village_green",
      ],
      paint: {
        "fill-color": "#d8ddd5",
        "fill-opacity": 0.4,
      },
    },
    {
      id: "landuse_pedestrian",
      type: "fill",
      source: SOURCE,
      "source-layer": "landuse",
      filter: ["==", "kind", "pedestrian"],
      paint: { "fill-color": "#dddad5", "fill-opacity": 0.3 },
    },

    // ── Water ───────────────────────────────────────────────────────
    {
      id: "water",
      type: "fill",
      source: SOURCE,
      "source-layer": "water",
      filter: ["==", "$type", "Polygon"],
      paint: { "fill-color": "#b8c8d4" },
    },
    {
      id: "water_river",
      type: "line",
      source: SOURCE,
      "source-layer": "water",
      minzoom: 9,
      filter: ["==", "kind", "river"],
      paint: {
        "line-color": "#b8c8d4",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          9,
          0.5,
          14,
          3,
          18,
          10,
        ],
      },
    },
    {
      id: "water_stream",
      type: "line",
      source: SOURCE,
      "source-layer": "water",
      minzoom: 14,
      filter: ["==", "kind", "stream"],
      paint: { "line-color": "#b8c8d4", "line-width": 0.5 },
    },

    // ── Hillshade ───────────────────────────────────────────────────
    {
      id: "hillshade",
      type: "hillshade",
      source: "terrain",
      paint: {
        "hillshade-illumination-direction": 315,
        "hillshade-exaggeration": 0.3,
        "hillshade-shadow-color": "#444444",
        "hillshade-highlight-color": "#ffffff",
        "hillshade-accent-color": "#cccccc",
      },
    },

    // ── Buildings ───────────────────────────────────────────────────
    {
      id: "buildings",
      type: "fill",
      source: SOURCE,
      "source-layer": "buildings",
      minzoom: 14,
      paint: { "fill-color": "#e0ddd8", "fill-opacity": 0.3 },
    },

    // ── Tunnel roads ────────────────────────────────────────────────
    {
      id: "roads_tunnels_other",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "is_tunnel", true],
        ["in", "kind", "other", "path"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          14,
          0,
          18,
          2,
        ],
        "line-opacity": 0.3,
        "line-dasharray": [4, 2],
      },
    },
    {
      id: "roads_tunnels_minor",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "is_tunnel", true],
        ["==", "kind", "minor_road"],
        ["!=", "kind_detail", "service"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          11,
          0,
          14,
          1,
          18,
          5,
        ],
        "line-opacity": 0.35,
        "line-dasharray": [4, 2],
      },
    },
    {
      id: "roads_tunnels_link",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: ["all", ["==", "is_tunnel", true], ["has", "is_link"]],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          15,
          1,
          18,
          5,
        ],
        "line-opacity": 0.35,
        "line-dasharray": [4, 2],
      },
    },
    {
      id: "roads_tunnels_major",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "is_tunnel", true],
        ["==", "kind", "major_road"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          6,
          0,
          12,
          1,
          15,
          2,
          18,
          8,
        ],
        "line-opacity": 0.35,
        "line-dasharray": [4, 2],
      },
    },
    {
      id: "roads_tunnels_highway",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "is_tunnel", true],
        ["==", "kind", "highway"],
        ["!has", "is_link"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          3,
          0,
          6,
          0.5,
          12,
          1.5,
          15,
          3,
          18,
          10,
        ],
        "line-opacity": 0.35,
        "line-dasharray": [4, 2],
      },
    },

    // ── Regular roads (no casing) ───────────────────────────────────
    {
      id: "roads_other",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["in", "kind", "other", "path"],
        ["!=", "kind_detail", "pier"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          14,
          0,
          18,
          2,
        ],
        "line-opacity": 0.7,
      },
    },
    {
      id: "roads_minor_service",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "minor_road"],
        ["==", "kind_detail", "service"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          18,
          4,
        ],
        "line-opacity": 0.7,
      },
    },
    {
      id: "roads_minor",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "minor_road"],
        ["!=", "kind_detail", "service"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          11,
          0,
          12.5,
          0.5,
          15,
          2,
          18,
          8,
        ],
        "line-opacity": 0.8,
      },
    },
    {
      id: "roads_link",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["has", "is_link"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          15,
          1,
          18,
          5,
        ],
        "line-opacity": 0.8,
      },
    },
    {
      id: "roads_major",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "major_road"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          6,
          0,
          12,
          1.2,
          15,
          3,
          18,
          10,
        ],
        "line-opacity": 0.85,
      },
    },
    {
      id: "roads_highway",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["!has", "is_tunnel"],
        ["!has", "is_bridge"],
        ["==", "kind", "highway"],
        ["!has", "is_link"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          3,
          0,
          6,
          0.8,
          12,
          1.6,
          15,
          4,
          18,
          12,
        ],
        "line-opacity": 0.85,
      },
    },

    // ── Bridge roads ────────────────────────────────────────────────
    {
      id: "roads_bridges_other",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "is_bridge", true],
        ["in", "kind", "other", "path"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          14,
          0,
          18,
          2,
        ],
        "line-opacity": 0.7,
      },
    },
    {
      id: "roads_bridges_minor",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "is_bridge", true],
        ["==", "kind", "minor_road"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          11,
          0,
          12.5,
          0.5,
          15,
          2,
          18,
          8,
        ],
        "line-opacity": 0.8,
      },
    },
    {
      id: "roads_bridges_link",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "is_bridge", true],
        ["has", "is_link"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          15,
          1,
          18,
          5,
        ],
        "line-opacity": 0.8,
      },
    },
    {
      id: "roads_bridges_major",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "is_bridge", true],
        ["==", "kind", "major_road"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          6,
          0,
          12,
          1.2,
          15,
          3,
          18,
          10,
        ],
        "line-opacity": 0.85,
      },
    },
    {
      id: "roads_bridges_highway",
      type: "line",
      source: SOURCE,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "is_bridge", true],
        ["==", "kind", "highway"],
        ["!has", "is_link"],
      ],
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          3,
          0,
          6,
          0.8,
          12,
          1.6,
          15,
          4,
          18,
          12,
        ],
        "line-opacity": 0.85,
      },
    },

    // ── Boundaries ──────────────────────────────────────────────────
    {
      id: "boundaries_country",
      type: "line",
      source: SOURCE,
      "source-layer": "boundaries",
      filter: ["<=", "kind_detail", 2],
      paint: {
        "line-color": "#9a9a9a",
        "line-width": 0.7,
        "line-dasharray": [3, 2],
      },
    },
    {
      id: "boundaries",
      type: "line",
      source: SOURCE,
      "source-layer": "boundaries",
      filter: [">", "kind_detail", 2],
      paint: {
        "line-color": "#b8b8b8",
        "line-width": 0.4,
        "line-dasharray": [3, 2],
      },
    },

    // ── Labels ──────────────────────────────────────────────────────
    {
      id: "water_label_ocean",
      type: "symbol",
      source: SOURCE,
      "source-layer": "places",
      filter: ["in", "kind", "sea", "ocean", "bay"],
      layout: {
        "text-font": ["Noto Sans Italic"],
        "text-field": ["get", "name:en"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 3, 10, 8, 16],
        "text-letter-spacing": 0.15,
        "text-transform": "uppercase",
        "text-max-width": 8,
      },
      paint: {
        "text-color": "#8a9bab",
        "text-halo-color": "#ddd8d3",
        "text-halo-width": 1,
      },
    },
    {
      id: "water_label_lakes",
      type: "symbol",
      source: SOURCE,
      "source-layer": "places",
      filter: ["in", "kind", "lake", "water"],
      minzoom: 10,
      layout: {
        "text-font": ["Noto Sans Italic"],
        "text-field": ["get", "name:en"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 10, 10, 16, 14],
        "text-max-width": 6,
      },
      paint: {
        "text-color": "#8a9bab",
        "text-halo-color": "#ddd8d3",
        "text-halo-width": 1,
      },
    },
    {
      id: "roads_labels_major",
      type: "symbol",
      source: SOURCE,
      "source-layer": "roads",
      minzoom: 13,
      filter: ["in", "kind", "highway", "major_road"],
      layout: {
        "text-font": ["Noto Sans Regular"],
        "text-field": ["get", "name:en"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 13, 10, 18, 14],
        "symbol-placement": "line",
        "symbol-spacing": 300,
        "text-max-angle": 30,
      },
      paint: {
        "text-color": "#8f8f8f",
        "text-halo-color": "#ebebeb",
        "text-halo-width": 1.5,
      },
    },
    {
      id: "roads_labels_minor",
      type: "symbol",
      source: SOURCE,
      "source-layer": "roads",
      minzoom: 15,
      filter: ["in", "kind", "minor_road", "other", "path"],
      layout: {
        "text-font": ["Noto Sans Regular"],
        "text-field": ["get", "name:en"],
        "text-size": 11,
        "symbol-placement": "line",
        "symbol-spacing": 200,
        "text-max-angle": 30,
      },
      paint: {
        "text-color": "#999999",
        "text-halo-color": "#e0e0e0",
        "text-halo-width": 1.5,
      },
    },
    {
      id: "places_subplace",
      type: "symbol",
      source: SOURCE,
      "source-layer": "places",
      filter: ["in", "kind", "neighbourhood", "macrohood"],
      minzoom: 12,
      layout: {
        "text-font": ["Noto Sans Regular"],
        "text-field": ["get", "name:en"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 12, 10, 16, 14],
        "text-transform": "uppercase",
        "text-letter-spacing": 0.1,
        "text-max-width": 6,
      },
      paint: {
        "text-color": "#7a7a7a",
        "text-halo-color": "#cccccc",
        "text-halo-width": 1,
      },
    },
    {
      id: "places_locality",
      type: "symbol",
      source: SOURCE,
      "source-layer": "places",
      filter: ["==", "kind", "locality"],
      layout: {
        "text-font": ["Noto Sans Bold"],
        "text-field": ["get", "name:en"],
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          4,
          8,
          8,
          14,
          12,
          18,
        ],
        "text-max-width": 8,
      },
      paint: {
        "text-color": "#474747",
        "text-halo-color": "#cccccc",
        "text-halo-width": 1.5,
      },
    },
    {
      id: "places_region",
      type: "symbol",
      source: SOURCE,
      "source-layer": "places",
      filter: ["==", "kind", "region"],
      minzoom: 5,
      maxzoom: 10,
      layout: {
        "text-font": ["Noto Sans Regular"],
        "text-field": ["get", "name:en"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 5, 9, 10, 13],
        "text-transform": "uppercase",
        "text-letter-spacing": 0.15,
        "text-max-width": 8,
      },
      paint: {
        "text-color": "#999999",
        "text-halo-color": "#cccccc",
        "text-halo-width": 1,
      },
    },
    {
      id: "places_country",
      type: "symbol",
      source: SOURCE,
      "source-layer": "places",
      filter: ["==", "kind", "country"],
      maxzoom: 8,
      layout: {
        "text-font": ["Noto Sans Bold"],
        "text-field": ["get", "name:en"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 2, 8, 6, 14],
        "text-transform": "uppercase",
        "text-letter-spacing": 0.15,
        "text-max-width": 6,
      },
      paint: {
        "text-color": "#858585",
        "text-halo-color": "#cccccc",
        "text-halo-width": 1.5,
      },
    },
  ],
};
